export const classUrlList = {
    "support": "https://wiki.gla.com.br/resouces/assets/images/icons/support.png",
    "slasher": "https://wiki.gla.com.br/resouces/assets/images/icons/slasher.png",
    "bruiser": "https://wiki.gla.com.br/resouces/assets/images/icons/bruiser.png",
    "specialist": "https://wiki.gla.com.br/resouces/assets/images/icons/specialist.png",
    "tank": "https://wiki.gla.com.br/resouces/assets/images/icons/tank.png",
    "fighter": "https://wiki.gla.com.br/resouces/assets/images/icons/fighter.png",
    "shooter": "https://wiki.gla.com.br/resouces/assets/images/icons/shooter.png",
    "dps": "https://wiki.gla.com.br/resouces/assets/images/icons/dps.png",
}

export const charClass = {
    "Buchi":[classUrlList.slasher, classUrlList.bruiser],
    "Cabaji":[classUrlList.slasher, classUrlList.dps],
    "Chew":[classUrlList.shooter, classUrlList.dps],
    "Alvida":[classUrlList.support, classUrlList.fighter],
    "Gin":[classUrlList.fighter, classUrlList.shooter, classUrlList.dps],
    "Hatchan":[classUrlList.slasher, classUrlList.support],
    "Jango":[classUrlList.fighter, classUrlList.support],
    "Kuroobi":[classUrlList.fighter, classUrlList.tank],
    "Mohji":[classUrlList.specialist, classUrlList.bruiser],
    "Morgan":[classUrlList.slasher, classUrlList.bruiser],
    "Pearl":[classUrlList.fighter, classUrlList.specialist, classUrlList.tank],
    "Eric":[classUrlList.shooter, classUrlList.slasher, classUrlList.dps],
    "Goldenweek":[classUrlList.support, classUrlList.specialist],
    "Mr.5":[classUrlList.shooter, classUrlList.dps],
    "Buggy":[classUrlList.shooter, classUrlList.dps],
    "Arlong":[classUrlList.fighter, classUrlList.bruiser],
    "Daddy":[classUrlList.shooter, classUrlList.dps],
    "Krieg":[classUrlList.shooter, classUrlList.dps],
    "Kuro":[classUrlList.slasher, classUrlList.dps],
    "Tashigi":[classUrlList.slasher, classUrlList.dps],
    "Vivi":[classUrlList.support, classUrlList.slasher],
    "Bepo":[classUrlList.fighter, classUrlList.dps],
    "Wapol":[classUrlList.shooter, classUrlList.tank],
    "Mr.3":[classUrlList.support, classUrlList.specialist],
    "Luffy":[classUrlList.fighter, classUrlList.bruiser],
    "Bastille":[classUrlList.slasher, classUrlList.tank],
    "Hawkins":[classUrlList.specialist, classUrlList.bruiser],
    "Brook":[classUrlList.slasher, classUrlList.support],
    "Kid":[classUrlList.shooter, classUrlList.tank],
    "Franky":[classUrlList.shooter, classUrlList.bruiser],
    "Nami":[classUrlList.specialist, classUrlList.dps],
    "Robin":[classUrlList.specialist, classUrlList.dps],
    "Zoro":[classUrlList.slasher, classUrlList.bruiser],
    "Smoker":[classUrlList.fighter, classUrlList.tank],
    "Chopper":[classUrlList.fighter, classUrlList.support],
    "Law":[classUrlList.slasher, classUrlList.specialist, classUrlList.dps],
    "Usopp":[classUrlList.shooter, classUrlList.dps],
    "Sanji":[classUrlList.fighter, classUrlList.dps],
    "Drake":[classUrlList.fighter, classUrlList.bruiser],
    "Apoo":[classUrlList.support, classUrlList.shooter],
    "Bonney":[classUrlList.support, classUrlList.fighter],
    "Capone":[classUrlList.shooter, classUrlList.dps],
    "Killer":[classUrlList.slasher, classUrlList.dps],
    "Urouge":[classUrlList.fighter, classUrlList.tank],
    "Hina":[classUrlList.fighter, classUrlList.bruiser],
    "Yonji":[classUrlList.fighter, classUrlList.tank],
    "Niji":[classUrlList.shooter, classUrlList.dps],
    "Reiju":[classUrlList.specialist, classUrlList.support],
    "Ichiji":[classUrlList.fighter, classUrlList.bruiser],
    "Bartolomeo":[classUrlList.specialist, classUrlList.dps],
    "Rebecca":[classUrlList.slasher, classUrlList.tank],
    "Leo":[classUrlList.support, classUrlList.specialist],
    "Koala":[classUrlList.fighter, classUrlList.dps],
    "Perona":[classUrlList.specialist, classUrlList.support],
    "Burgess":[classUrlList.fighter, classUrlList.tank],
    "Shanks":[classUrlList.slasher, classUrlList.bruiser],
    "Mihawk":[classUrlList.slasher, classUrlList.dps],
    "Hancock":[classUrlList.fighter, classUrlList.dps],
    "Kuma":[classUrlList.specialist, classUrlList.tank],
    "Jinbe":[classUrlList.fighter, classUrlList.tank],
    "Barba negra": [classUrlList.specialist, classUrlList.bruiser],
    "Doflamingo":[classUrlList.shooter, classUrlList.specialist, classUrlList.dps],
    "Ace":[classUrlList.shooter, classUrlList.specialist, classUrlList.dps]
}