export const islandUrlList = {
    "foosha":"https://wiki.gla.com.br/resouces/assets/images/island/foosha.png",
    "shellstown":"https://wiki.gla.com.br/resouces/assets/images/island/shell.png",
    "samui":"https://wiki.gla.com.br/resouces/assets/images/island/samui.png",
    "orange":"https://wiki.gla.com.br/resouces/assets/images/island/orange.png",
    "syrup":"https://wiki.gla.com.br/resouces/assets/images/island/syrup.png",
    "baratie":"https://wiki.gla.com.br/resouces/assets/images/island/baratie.png",
    "rare island":"https://wiki.gla.com.br/resouces/assets/images/island/rare.png",
    "cocoyasi":"https://wiki.gla.com.br/resouces/assets/images/island/cocoyasi.png",
    "loguetown":"https://wiki.gla.com.br/resouces/assets/images/island/loguetown.png",
    "kumo":"https://wiki.gla.com.br/resouces/assets/images/island/kumo.png",
    "reverse":"https://wiki.gla.com.br/resouces/assets/images/island/reverse.png",
    "whiskypeak":"https://wiki.gla.com.br/resouces/assets/images/island/whiskypeak.png",
    "littlegarden":"https://wiki.gla.com.br/resouces/assets/images/island/littlegarden.png",
    "g7":"https://wiki.gla.com.br/resouces/assets/images/island/g7-2.png",
    "drum":"https://wiki.gla.com.br/resouces/assets/images/island/drum.png",
    "nanimonai":"https://wiki.gla.com.br/resouces/assets/images/island/nanimonai.png",
    "nihon2":"https://wiki.gla.com.br/resouces/assets/images/island/nihon2.png",
    "alabastawest":"https://wiki.gla.com.br/resouces/assets/images/island/alabastawest.png",
    "alabastaeast":"https://wiki.gla.com.br/resouces/assets/images/island/alabastaeast.png"
}